version: '3.6'
services:

  lbalancer:
    build:
      context: .
      dockerfile: balancer.Dockerfile
    container_name: lbalancer
    entrypoint: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
    volumes:
      - ./GeoLite2-Country.mmdb:/etc/nginx/GeoLite2-Country.mmdb
      - ./balancer.conf:/etc/nginx/nginx.conf
    networks:
      app_net:
        ipv4_address: 100.0.0.10

  nodeuk:
    image: nginx:latest
    container_name: node_uk
    hostname: nodeuk
    ports:
      - "85:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf.tmp
    environment:
      - NODE_NAME=UK NODE
    command: /bin/bash -c "envsubst < ./nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      app_net:
        ipv4_address: 100.0.0.11

  nodeus1:
    image: nginx:latest
    container_name: node_us_1
    hostname: node_us_1
    ports:
      - "86:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf.tmp
    environment:
      - NODE_NAME=US NODE 1
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf.tmp > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      app_net:
        ipv4_address: 100.0.0.12

  nodeus2:
    image: nginx:latest
    container_name: node_us_2
    hostname: node_us_2
    ports:
      - "87:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf.tmp
    environment:
      - NODE_NAME=US NODE 2
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf.tmp > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      app_net:
        ipv4_address: 100.0.0.13

  nodeother:
    image: nginx:latest
    container_name: node_other_3
    ports:
      - "88:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf.tmp
    environment:
      - NODE_NAME=NODE FOR ALL
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf.tmp > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      app_net:
        ipv4_address: 100.0.0.14

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 100.0.0.0/14
